package friendfinder.services.controller;

import friendfinder.api.domain.Account;
import friendfinder.api.domain.User;
import friendfinder.api.exceptions.HttpConflictException;
import friendfinder.api.exceptions.HttpNotFoundException;
import friendfinder.api.exceptions.HttpUnprocessableEntityException;
import friendfinder.persistence.AccountRepository;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;
import static org.apache.commons.lang3.StringUtils.isBlank;

/**
 * Created by grace on 23/06/17.
 */
@RestController    // This means that this class is a Controller
@RequestMapping(path="/account") // This means URL's start with /account (after Application path)
public class AccountResourceImpl {

    private static final Logger log = LoggerFactory.getLogger(AccountResourceImpl.class);

    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private AccountRepository accountRepository;

    @GetMapping(path="/all")
    public Iterable<Account> getAllAccounts() {
        // This returns a JSON with the accounts
        log.debug("Getting all accounts");

        return accountRepository.findAll();
    }

    /**
     * The REST call needs to return a JSON object for the FrontEnd. This way the FrontEnd can
     * use the returned object and do operations on it.
     * @param email
     * @param password
     * @return
     */
    @GetMapping
    public Account loginAccount (@RequestParam(value = "email") String email,
                              @RequestParam(value = "password") String password) {
        log.debug("Getting the account by email and password");
        Account serchedEntity = null;
            if (isBlank(email) || isBlank(password)) {
                throw new HttpUnprocessableEntityException("Email or password is blank.");
            }
            serchedEntity = accountRepository.findByEmailAndPassword(email, password);

            if (serchedEntity == null) {
                log.debug("Account does not exist.");
                throw new HttpNotFoundException("Entity was not found");
            }
        return serchedEntity;
    }

    @PostMapping
    public Account registerAccount (@RequestBody Account entity) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

            if (entity == null || isBlank(entity.getEmail()) || isBlank(entity.getPassword())) {
                throw new HttpUnprocessableEntityException("Entity, email or password is blank.");
            }
            Account searchedEntity = accountRepository.findByEmail(entity.getEmail());

            if (searchedEntity != null) {
                log.debug("Entity already registered.");
                throw new HttpConflictException("Entity already registered.");
            }
            log.debug("Creating an Entity");

            User usr = new User();
            usr.setAccount(entity);
            entity.setUser(usr);
            Account newEntity = accountRepository.save(entity);
        return newEntity;
    }

    @PutMapping(value = "/{accountId}")
    public Account updateAccount (@PathVariable(value = "accountId") Integer accountId,
                                 @RequestBody Account entity) {
        log.debug("Updating the Entity");
        Account entityBefore = null;
            entityBefore = accountRepository.findById(accountId);
            if (entityBefore == null) {
                throw new HttpNotFoundException("The Entity was not found");
            }
            entity.setId(accountId);
            entity.setCreatedAt(entityBefore.getCreatedAt());
            entityBefore = accountRepository.save(entity);
        return entityBefore;
    }

    @DeleteMapping(value = "/{accountId}")
    public void deleteAccount (@PathVariable(value = "accountId") Integer accountId) {
        log.debug("Deleting an account");
        Account deleteEntity = null;
            deleteEntity = accountRepository.findById(accountId);
            if (deleteEntity == null) {
                throw new HttpNotFoundException("The Entity was not found.");
            }
            accountRepository.delete(deleteEntity);
    }
}
